PrototypeApp({
  name:'星链 CRM',en:'CUSTOMER RELATIONSHIP',color:'#4f46e5',color2:'#7c3aed',user:'林知夏',role:'销售主管',badge:12,
  greeting:'上午好，林知夏',subtitle:'聚焦高价值客户，让每一次跟进都有结果。',entity:'商机',metricLabel:'预计金额',
  nav:['销售工作台','线索管理','客户管理','联系人','商机管道','合同回款','任务日程','数据分析','系统设置'],
  kpis:[{label:'本月新增线索',value:'286',trend:'↑ 18.2%'},{label:'进行中商机',value:'¥ 428万',trend:'↑ 12.6%'},{label:'预计成交额',value:'¥ 196万',trend:'↑ 8.4%'},{label:'本月已回款',value:'¥ 118万',trend:'↓ 3.1%',down:true}],
  chartTitle:'销售预测与实际成交',donutTitle:'商机阶段分布',focusTitle:'高价值商机',categories:['需求确认','方案沟通','商务谈判'],
  rows:[{name:'澄海科技数字化升级',code:'OPP-202607-0182',status:'商务谈判',value:'¥ 680,000',progress:82,owner:'林知夏'},{name:'远望医疗客户平台',code:'OPP-202607-0175',status:'方案沟通',value:'¥ 460,000',progress:64,owner:'陈予安'},{name:'启明智造营销中台',code:'OPP-202606-0158',status:'需求确认',value:'¥ 320,000',progress:38,owner:'宋嘉禾'},{name:'新桥物流数据项目',code:'OPP-202606-0141',status:'合同审核',value:'¥ 890,000',progress:91,owner:'周景行'},{name:'星云零售会员系统',code:'OPP-202605-0126',status:'风险关注',value:'¥ 275,000',progress:31,owner:'林知夏'}],
  activities:['澄海科技商机推进至「商务谈判」','陈予安完成远望医疗方案演示','合同 HT-2026-0712 收到首笔回款','宋嘉禾新增一条客户拜访记录','系统识别到 3 条长期未跟进商机'],
  pages:{
    1:{entity:'线索',description:'管理线索来源、评分、分配与转化，避免重复触达和机会遗漏。',metricLabel:'线索评分',ownerLabel:'负责人',primaryAction:'新建线索',codePrefix:'LEAD',initialStatus:'新建',activeStatus:'培育中',advanceAction:'转化线索',categories:['官网咨询','市场活动','客户转介绍'],statuses:['新建','已联系','培育中','已转化'],rows:[{name:'王珂 · 华辰新能源',code:'LEAD-260708-086',status:'待首次联系',value:'92 分',progress:18,owner:'宋嘉禾'},{name:'赵明 · 霁云数据',code:'LEAD-260708-079',status:'培育中',value:'78 分',progress:46,owner:'林知夏'},{name:'陈露 · 谱元生物',code:'LEAD-260707-065',status:'转化评估',value:'85 分',progress:72,owner:'陈予安'}]},
    2:{entity:'客户',description:'客户 360° 档案，汇总联系人、商机、合同、回款和健康度。',metricLabel:'客户等级',ownerLabel:'客户经理',primaryAction:'新建客户',codePrefix:'ACC',initialStatus:'待完善',activeStatus:'合作中',advanceAction:'更新客户等级',categories:['战略客户','重点客户','普通客户'],rows:[{name:'澄海科技有限公司',code:'ACC-000218',status:'合作中',value:'A 级',progress:86,owner:'林知夏'},{name:'远望医疗集团',code:'ACC-000205',status:'重点跟进',value:'A 级',progress:73,owner:'陈予安'},{name:'启明智能制造',code:'ACC-000197',status:'培育中',value:'B 级',progress:51,owner:'宋嘉禾'}]},
    3:{entity:'联系人',description:'维护客户关键联系人、决策角色、沟通偏好和影响力。',metricLabel:'决策角色',ownerLabel:'所属客户',primaryAction:'新建联系人',codePrefix:'CONT',initialStatus:'有效',activeStatus:'已验证',advanceAction:'标记关键人',categories:['决策人','影响人','使用人'],rows:[{name:'顾明远 · CIO',code:'CONT-001286',status:'关键联系人',value:'决策人',progress:92,owner:'澄海科技'},{name:'叶舒 · 采购总监',code:'CONT-001271',status:'已验证',value:'影响人',progress:76,owner:'远望医疗'},{name:'孙航 · 信息经理',code:'CONT-001244',status:'待沟通',value:'使用人',progress:43,owner:'启明智造'}]},
    4:{kind:'kanban',entity:'商机',description:'按销售阶段推进商机，管理金额、赢率、风险和下一步行动。',metricLabel:'预计金额',ownerLabel:'销售负责人',primaryAction:'新建商机',codePrefix:'OPP',initialStatus:'需求确认',activeStatus:'商务推进',reviewStatus:'合同审核',advanceAction:'推进商机阶段',categories:['需求确认','方案沟通','商务谈判'],kanban:['需求确认','方案与谈判','合同/赢单'],rows:[{name:'澄海科技数字化升级',code:'OPP-202607-0182',status:'商务谈判',value:'¥ 680,000',progress:82,owner:'林知夏'},{name:'远望医疗客户平台',code:'OPP-202607-0175',status:'方案沟通',value:'¥ 460,000',progress:64,owner:'陈予安'},{name:'启明智造营销中台',code:'OPP-202606-0158',status:'需求确认',value:'¥ 320,000',progress:38,owner:'宋嘉禾'}]},
    5:{entity:'合同',description:'跟踪合同审批、履约、回款计划与到账进度。',metricLabel:'合同金额',ownerLabel:'合同负责人',progressLabel:'回款进度',primaryAction:'新建合同',codePrefix:'HT',initialStatus:'草稿',activeStatus:'履行中',reviewStatus:'审核中',advanceAction:'登记回款',categories:['销售合同','框架合同','服务合同'],statuses:['草稿','审核中','履行中','已完成'],rows:[{name:'澄海科技平台建设合同',code:'HT-2026-0712',status:'履行中',value:'¥ 680,000',progress:60,owner:'林知夏'},{name:'远望医疗一期服务合同',code:'HT-2026-0688',status:'审核中',value:'¥ 280,000',progress:35,owner:'陈予安'},{name:'新桥物流数据服务合同',code:'HT-2026-0619',status:'回款逾期',value:'¥ 890,000',progress:72,owner:'周景行'}]},
    6:{kind:'calendar',entity:'任务',description:'集中管理跟进任务、客户拜访、电话和合同节点。',metricLabel:'截止时间',ownerLabel:'执行人',primaryAction:'新建任务',codePrefix:'TASK',initialStatus:'待处理',activeStatus:'进行中',advanceAction:'完成任务',categories:['客户拜访','电话跟进','合同节点'],rows:[{name:'澄海科技合同条款确认',code:'TASK-260708-31',status:'今日到期',value:'今天 16:00',progress:72,owner:'林知夏'},{name:'远望医疗方案演示',code:'TASK-260709-18',status:'已安排',value:'明天 10:30',progress:48,owner:'陈予安'},{name:'启明智造高层拜访',code:'TASK-260710-09',status:'待确认',value:'周五 14:00',progress:26,owner:'宋嘉禾'}]},
    7:{kind:'analytics',entity:'销售指标',description:'按团队、人员、阶段和来源分析漏斗、预测及回款表现。',metricLabel:'指标值',ownerLabel:'统计口径',chartTitle:'销售额与预测趋势',donutTitle:'商机来源构成',categories:['市场活动','转介绍','主动开发'],kpis:[{label:'销售预测',value:'¥ 428万',trend:'↑ 12.6%'},{label:'赢单率',value:'34.8%',trend:'↑ 3.2%'},{label:'平均销售周期',value:'42天',trend:'↓ 5天'},{label:'回款达成率',value:'88.5%',trend:'↑ 4.1%'}],rows:[{name:'华东团队赢单率',code:'METRIC-WIN-01',status:'优于目标',value:'38.6%',progress:88,owner:'本季度'},{name:'高价值商机覆盖',code:'METRIC-PIPE-02',status:'需关注',value:'2.4×',progress:64,owner:'本月'},{name:'回款计划达成',code:'METRIC-PAY-03',status:'正常',value:'88.5%',progress:89,owner:'本月'}]},
    8:{kind:'settings',entity:'系统配置',description:'配置组织用户、角色权限、商机阶段、字段字典和审计策略。',metricLabel:'当前配置',ownerLabel:'维护人',categories:['权限','业务规则','数据'],rows:[{name:'用户与角色权限',code:'SET-RBAC',status:'已启用',value:'4 个角色',progress:100,owner:'系统管理员'},{name:'商机阶段与赢率',code:'SET-STAGE',status:'已发布',value:'4 个阶段',progress:100,owner:'销售运营'},{name:'客户字段与查重规则',code:'SET-FIELD',status:'待更新',value:'26 个字段',progress:68,owner:'销售运营'},{name:'审计日志与数据保留',code:'SET-AUDIT',status:'运行中',value:'保留 180 天',progress:100,owner:'系统管理员'}]}
  },
  roles:[{name:'销售主管',user:'林知夏',scope:'全部数据',nav:[0,1,2,3,4,5,6,7,8],permissions:['create','edit','export','advance']},{name:'销售代表',user:'宋嘉禾',scope:'个人数据',nav:[0,1,2,3,4,5,6],permissions:['create','edit','advance']},{name:'财务协同',user:'顾言川',scope:'财务相关数据',nav:[0,5,7],permissions:['export','advance']},{name:'系统管理员',user:'唐知微',scope:'全部数据',nav:[0,1,2,3,4,5,6,7,8],permissions:['export']}]
});
